Docker 1
Otus-DevOps-2018-05/n3tdom_microservices pull request #1
Opened 2018-08-12 21:58 UTC by n3tdom

# Выполнено ДЗ docker-1
 - [x] Основное ДЗ
 - [x] Задание со *
## В процессе сделано:
### Основное задание
Установлен докер, знакомство с основными командами

### Задание со * -
>На основе вывода команд объясните чем отличается контейнер от образа

1. Единственная одинаковая для образа и контейнера секция в выводе docker inspect - содержит информацию о хосте и среде где создан image/container: hostname, attachStd, env, cmd, parent image.
2. Образ представляет из себя набор слоев, вывод команды указывает их список, название образа в репозитории, образ на основе которого он создавался
3. Контейнер являет собой уже готовый к запуску объект с сетевыми интерфейсами, маунтами и другими свойствами относительно docker daemon

## Как запустить проект:
 -
## Как проверить работоспособность:
 -
## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-09-03 12:00 UTC, hostberg requested changes
Все отлично, но не отработали проверки travis'а, нужно пофиксить.

2018-09-04 17:27 UTC, n3tdom commented
@hostberg 
Файл travis.yml я добавил в этом PR, как исправить то, что чек не работает?

Правильно ли понимаю что нужно создать еще один PR чисто про travis.yml что бы приняли вначале его, а затем уже тут заработает проверка?

2018-09-05 06:54 UTC, hostberg commented
Имя файла должно начинаться с точки (.travis.yml).

2018-09-09 12:09 UTC, n3tdom commented
Стыдно, пофиксил

2018-09-24 11:14 UTC, n3tdom commented
Жду апрува @hostberg

2018-09-24 11:51 UTC, hostberg approved these changes

2018-09-24 15:14 UTC, merged