Docker 4
Otus-DevOps-2018-05/n3tdom_microservices pull request #4
Opened 2018-09-04 17:18 UTC by n3tdom

# Выполнено ДЗ docker-4
 - [x] Основное ДЗ
 - [x] Задание со * #1

### Основное задание
- Работа с сетями в Docker
- Использование docker-compose

### Задание со * - docker-compose.override.yml Дебаг и редактирование соурс кода без ребилда образа
- Параметры запуска передаются с помощьюh ttps://docs.docker.com/v17.09/compose/compose-file/#entrypoint При этом CMD[] внутри Dockerfile игнорируется
- При запуске команды из второго -f дополняют/перезаписывают команды в первом
```docker-compose -f docker-compose.yml -f docker-compose-override.yml up -d```

TODO: Волюмы не создаются и приложение лежит
## Как запустить проект:
docker-compose -f docker-compose.yml up -d

## Как проверить работоспособность:
Зайти по адресу из docker-machine ls , порт 9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-09-04 17:19 UTC, n3tdom commented
Вопрос по ДЗ со *. При вызове оверрайд файла не создаются волюмы из него. Как траблшутить?
docker-compose -f docker-compose.yml -f docker-compose-override.yml up -d

2018-10-08 09:33 UTC, WeitBelou commented
> Вопрос по ДЗ со *. При вызове оверрайд файла не создаются волюмы из него.
> docker-compose -f docker-compose.yml -f docker-compose-override.yml up -d
> 
> Как траблшутить? docker-compose logs , docker inspect <упавший контейнер> новой инфы не дают

У меня всё вроде бы запустилось, можно попробовать проверить не висит ли где-то volume с таким же названием и на всякий случай прогнать:
```bash
docker system prune --volumes
```

2018-10-08 09:36 UTC, grim-yawn requested changes
Отписал в комментариях

2018-10-31 20:31 UTC, n3tdom commented
Перепроверил, действительно волюм мешал, все работает

2018-11-01 08:40 UTC, grim-yawn approved these changes

2018-11-01 13:51 UTC, merged